theme: jekyll-theme-dinky
title: "Daily Archive"
description: "I use this mostly to keep track of the latest cool stuffs in the realms of machine learning, quantitative finance and actuarial science

